In [1]:
import numpy as np

In [2]:
v_hor_np = np.array([1, 2])
print(v_hor_np)

[1 2]


In [4]:
v_hor_zeros_v2 = np.zeros((1, 5))
print(v_hor_zeros_v2)

[[0. 0. 0. 0. 0.]]


In [5]:
v_hor_one_v1 = np.ones((5,))
print(v_hor_one_v1)

[1. 1. 1. 1. 1.]


In [6]:
v_hor_one_v2 = np.ones((1, 5))
print(v_hor_one_v2)

[[1. 1. 1. 1. 1.]]


In [7]:
v_vert_np = np.array([[1], [2]])
print(v_vert_np)

[[1]
 [2]]


In [8]:
v_vert_zeros = np.zeros((5, 1))
print(v_vert_zeros)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [9]:
v_vert_ones = np.ones((5, 1))
print(v_vert_ones)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [10]:
m_sqr_arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(m_sqr_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
m_sqr = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
m_sqr_arr = np.array(m_sqr)
print(m_sqr_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
m_sqr_mx = np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(m_sqr_mx)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
m_sqr_mx = np.matrix('1 2 3; 4 5 6; 7 8 9')
print(m_sqr_mx)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
m_diag = [[1, 0, 0], [0, 5, 0], [0, 0, 9]]
m_diag_np = np.matrix(m_diag)
print(m_diag)

[[1, 0, 0], [0, 5, 0], [0, 0, 9]]


In [16]:
m_sqr_mx = np.matrix('1 2 3; 4 5 6; 7 8 9')

In [17]:
diag = np.diag(m_sqr_mx)
print(diag)

[1 5 9]


In [18]:
m_diag_np = np.diag(np.diag(m_sqr_mx))
print(m_diag_np)

[[1 0 0]
 [0 5 0]
 [0 0 9]]


In [19]:
m_e = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
m_e_np = np.matrix(m_e)
print(m_e_np)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [20]:
m_eye = np.eye(3)
print(m_eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [21]:
m_idnt = np.identity(3)
print(m_idnt)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
m_zeros = np.zeros((3, 3))
print(m_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [23]:
m_mx = np.matrix('1 2 3; 4 5 6')
print(m_mx)

[[1 2 3]
 [4 5 6]]


In [24]:
m_var = np.zeros((2, 5))
print(m_var)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [25]:
A = np.matrix('1 2 3; 4 5 6')
print(A)

[[1 2 3]
 [4 5 6]]


In [26]:
A_t = A.transpose()
print(A_t)

[[1 4]
 [2 5]
 [3 6]]


In [27]:
print(A.T)

[[1 4]
 [2 5]
 [3 6]]


In [30]:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
L = (A.dot(B)).T
R = (B.T).dot(A.T)
print(L)
print()
print(R)

[[19 43]
 [22 50]]

[[19 43]
 [22 50]]


In [32]:
A = np.matrix('1 2; 3 4')
A_det = np.linalg.det(A)
A_T_det = np.linalg.det(A.T)
print(format(A_det, '.9g'))
print()
print(format(A_T_det, '.9g'))

-2

-2


In [33]:
A = np.matrix('1 2 3; 4 5 6')
C = 3 * A
print(C)

[[ 3  6  9]
 [12 15 18]]


In [34]:
A = np.matrix('1 2; 3 4')
L = 1 * A
R = A

In [35]:
print(L)

[[1 2]
 [3 4]]


In [36]:
print(R)

[[1 2]
 [3 4]]


In [38]:
A = np.matrix('1 2; 3 4')
Z = np.matrix('0 0; 0 0')
L = 0 * A
R = Z
print(L)

[[0 0]
 [0 0]]


In [39]:
print(R)

[[0 0]
 [0 0]]


In [40]:
A = np.matrix('1 6 3; 8 2 7')
B = np.matrix('8 1 5; 6 9 12')
C = A + B
print(C)

[[ 9  7  8]
 [14 11 19]]


In [41]:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
L = A + B
R = B + A
print(L)

[[ 6  8]
 [10 12]]


In [42]:
print(R)

[[ 6  8]
 [10 12]]


In [43]:
A = np.matrix('1 2 3; 4 5 6')
B = np.matrix('7 8; 9 1; 2 3')
C = A.dot(B)
print(C)

[[31 19]
 [85 55]]


In [45]:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
C = np.matrix('2 4; 7 8')
L = A.dot(B.dot(C))
R = (A.dot(B)).dot(C)
print(L)

[[192 252]
 [436 572]]


In [46]:
print(R)

[[192 252]
 [436 572]]


In [47]:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
C = np.matrix('2 4; 7 8')
L = A.dot(B + C)
R = A.dot(B) + A.dot(C)
print(L)

[[35 42]
 [77 94]]


In [48]:
print(R)

[[35 42]
 [77 94]]


In [49]:
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
print(A)

[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]


In [50]:
np.linalg.det(A)

-14.000000000000009

In [51]:
print(A.T)

[[-4 10  8]
 [-1  4  3]
 [ 2 -1  1]]


In [52]:
det_A = round(np.linalg.det(A), 3)
det_A_t = round(np.linalg.det(A.T), 3)

In [53]:
print(det_A)

-14.0


In [54]:
print(det_A_t)

-14.0


In [56]:
A = np.matrix('1 -3; 2 5')
A_inv = np.linalg.inv(A)
print(A)

[[ 1 -3]
 [ 2  5]]


In [57]:
print(A_inv)

[[ 0.45454545  0.27272727]
 [-0.18181818  0.09090909]]


In [58]:
A = np.matrix('1. -3.; 2. 5.')
L = np.linalg.inv(A.T)
R = (np.linalg.inv(A)).T
print(L)

[[ 0.45454545 -0.18181818]
 [ 0.27272727  0.09090909]]


In [59]:
print(R)

[[ 0.45454545 -0.18181818]
 [ 0.27272727  0.09090909]]


In [60]:
A = np.matrix('1. -3.; 2. 5.')
B = np.matrix('7. 6.; 1. 8.')
L = np.linalg.inv(A.dot(B))
R = np.linalg.inv(B).dot(np.linalg.inv(A))
print(L)

[[ 0.09454545  0.03272727]
 [-0.03454545  0.00727273]]


In [61]:
print(R)

[[ 0.09454545  0.03272727]
 [-0.03454545  0.00727273]]


In [63]:
m_eye = np.eye(4)
print(m_eye)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [64]:
rank = np.linalg.matrix_rank(m_eye)
print(rank)

4


In [65]:
m_eye[3][3] = 0
print(m_eye)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]]


In [66]:
rank = np.linalg.matrix_rank(m_eye)
print(rank)

3
