In [10]:
import numpy as np

## Решение матричным методом

In [21]:
M = np.matrix('1 5 6; 2 5 1; -3 2 7')
V = np.matrix ('3; -4; 1')

Теперь необходимо проверить является ли матрица вырожденной (определитель равен 0) от этого будет зависеть сможем ли вообще использовать матричный метод для решения данного уравнения

In [22]:
opr = np.linalg.det(M)
print(opr)

62.00000000000001


Определитель не равен 0

Найдем матрицу, обратную матрице коэффициентов при неизвестных

In [23]:
m_inv = np.linalg.inv(M)
print(m_inv)

[[ 0.53225806 -0.37096774 -0.40322581]
 [-0.27419355  0.40322581  0.17741935]
 [ 0.30645161 -0.27419355 -0.08064516]]


Найдем матрицу не известных по формуле $ X = M^{-1} * V$

In [25]:
m_inv.dot(V)

matrix([[ 2.67741935],
        [-2.25806452],
        [ 1.93548387]])

В библиотеке numpy для решения систем уравнений матричным методом используется функция solve из linalg, проверим правильность решения с помощью этой функции

In [26]:
np.linalg.solve(M,V)

matrix([[ 2.67741935],
        [-2.25806452],
        [ 1.93548387]])

Значения совпадают

## Решение методом Крамера

Решим выше указанное уравнение методом Крамера

Для начала объявим необходимые матрицы, а именно матрицу коэффициентов при неизвестных, матрицу свободных членов и матрицу которая будет возвращать первоначальные значения изменённому столбцу. Так же зададим список для определителей полученных в ходе подстановки значений из матрицы свободных членов в матрицу коэффициентов при неизвестных.

In [36]:
M = np.matrix('1 5 6; 2 5 1; -3 2 7')
V = np.matrix ('3; -4; 1')
check_matrix = np.matrix('0;0;0')
dets = []

Посчитаем изначальный определитель матрицы коэффициентов при неизвестных, его так же называют главным определителем

In [37]:
main_det = np.linalg.det(M)

In [38]:
i = 0
while i < len(M):
    check_matrix[:, 0] = M[:, i]
    M[:, i] = V[:, 0]
    temp_det = np.linalg.det(M)
    dets.append(temp_det)
    M[:, i] = check_matrix[:, 0]
    i += 1


Теперь осталось только сделать из полученного списка numpy массив и разделить каждый элемент этого массива на главный определитель

In [39]:
dets = np.array(dets)
result = dets // main_det
print(result)

[ 2. -3.  1.]


Полученная матрица сходится с результатами предыдущего метода, из чего можно сделать вывод, что алгоритм работает корректно.