In [10]:
import numpy as np

## Транспонирование матрицы

Свойство 1. Дважды транспонированная матрица равна исходной матрице.

In [12]:
x = np.matrix('18 0 -9; 5 1 12; 10 1 -9')
t_mrx = (x.T).T
print(t_mrx)

[[18  0 -9]
 [ 5  1 12]
 [10  1 -9]]


Свойство 2. Транспонирование суммы матриц равно сумме транспонированных матриц

In [13]:
x = np.matrix('18 0 -9; 5 1 12; 10 1 -9')
y = np.matrix('9 -5 10; 7 1 0; 9 2 -5')
first = (x + y).T
second = x.T + y.T
print(first)
print(second)

[[ 27  12  19]
 [ -5   2   3]
 [  1  12 -14]]
[[ 27  12  19]
 [ -5   2   3]
 [  1  12 -14]]


Свойство 3. Транспонирование произведения матриц равно произведению транспонированных матриц расставленных в обратном порядке:

In [16]:
x = np.matrix('18 5 -9; 5 1 12; 10 1 -9')
y = np.matrix('9 -5 10; 7 1 0; 9 2 -5')
first_mrx = (x.dot(y)).T
sec_mrx = (y.T).dot(x.T)
print(first_mrx)
print(sec_mrx)

[[ 116  160   16]
 [-103    0  -67]
 [ 225  -10  145]]
[[ 116  160   16]
 [-103    0  -67]
 [ 225  -10  145]]


Свойство 4. Транспонирование произведения матрицы на число равно произведению этого числа на транспонированную матрицу:

In [17]:
x = np.matrix('18 5 -9; 5 1 12; 10 1 -9')
g = 5
first_mrx = g * (x.T)
sec_mrx = (g * x).T
print(first_mrx)
print(sec_mrx)

[[ 90  25  50]
 [ 25   5   5]
 [-45  60 -45]]
[[ 90  25  50]
 [ 25   5   5]
 [-45  60 -45]]


*Свойство 5*. Определители исходной и транспонированной матрицы совпадают:

In [18]:
x = np.matrix('18 5 -9; 5 1 12; 10 1 -9')
x_det = np.linalg.det(x)
x_T_det = np.linalg.det(x.T)
print(format(x_det, '.9g'))
print(format(x_T_det, '.9g'))

492
492


# Умножение матрицы на число

Свойство 1. Произведение единицы и любой заданной матрицы равно заданной матрице:

In [25]:
A = np.matrix('18 5 -9; 5 1 12; 10 1 -9')
L = 1 * A
R = A
print(L)
print(R)

[[18  5 -9]
 [ 5  1 12]
 [10  1 -9]]
[[18  5 -9]
 [ 5  1 12]
 [10  1 -9]]


Свойство 2. Произведение нуля и любой матрицы равно нулевой матрице, размерность которой равна исходной матрицы:

In [26]:
A = np.matrix('18 5 -9; 5 1 12; 10 1 -9')
Z = np.matrix('0 0 0; 0 0 0; 0 0 0')
L = 0 * A
print(L)
print(Z)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


Свойство 3. Произведение матрицы на сумму чисел равно сумме произведений матрицы на каждое из этих чисел:

In [28]:
A = np.matrix('15 9 -5; -3 10 11; 2 1 4')
p = 21
q = 12
L = (p + q) * A
R = p * A + q * A
print(L)
print(R)

[[ 495  297 -165]
 [ -99  330  363]
 [  66   33  132]]
[[ 495  297 -165]
 [ -99  330  363]
 [  66   33  132]]


Свойство 4. Произведение матрицы на произведение двух чисел равно произведению второго числа и заданной матрицы, умноженному на первое число:

In [29]:
A = np.matrix('1 2; 3 4')
p = 5
q = 6
L = (p * q) * A
R = p * (q * A)
print(L)
print(R)

[[ 30  60]
 [ 90 120]]
[[ 30  60]
 [ 90 120]]


Свойство 5. Произведение суммы матриц на число равно сумме произведений этих матриц на заданное число:

In [30]:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
k = 3
L = k * (A + B)
R = k * A + k * B
print(L)
print(R)

[[18 24]
 [30 36]]
[[18 24]
 [30 36]]


# Сложение матриц

Свойство 1. Коммутативность сложения. От перестановки матриц их сумма не изменяется:

In [31]:
A = np.matrix('12 7; 8 11')
B = np.matrix('5 5; 9 3')
L = A + B
R = B + A
print(L)
print(R)

[[17 12]
 [17 14]]
[[17 12]
 [17 14]]


Свойство 2. Ассоциативность сложения. Результат сложения трех и более матриц не зависит от порядка, в котором эта операция будет выполняться:

In [32]:
A = np.matrix('12 7; 8 11')
B = np.matrix('5 5; 9 3')
C = np.matrix('11 2; 8 9')
L = A + (B + C)
R = (A + B) + C
print(L)
print(R)

[[28 14]
 [25 23]]
[[28 14]
 [25 23]]


Свойство 3. Для любой матрицы существует противоположная ей , такая, что их сумма является нулевой матрицей:

In [33]:
A = np.matrix('12 7; 8 11')
Z = np.matrix('0 0; 0 0')
L = A + (-1)*A
print(L)

[[0 0]
 [0 0]]


# Умножение матриц

Свойство 1. Ассоциативность умножения. Результат умножения матриц не зависит от порядка, в котором будет выполняться эта операция:

In [34]:
A = np.matrix('12 7; 8 11')
B = np.matrix('5 5; 9 3')
C = np.matrix('11 2; 8 9')
L = A.dot(B.dot(C))
R = (A.dot(B)).dot(C)
print(L)
print(R)

[[2001  975]
 [2113  935]]
[[2001  975]
 [2113  935]]


Свойство 2. Дистрибутивность умножения. Произведение матрицы на сумму матриц равно сумме произведений матриц:

In [35]:
A = np.matrix('12 7; 8 11')
B = np.matrix('5 5; 9 3')
C = np.matrix('11 2; 8 9')
L = A.dot(B + C)
R = A.dot(B) + A.dot(C)
print(L)
print(R)

[[311 168]
 [315 188]]
[[311 168]
 [315 188]]


Свойство 3. Умножение матриц в общем виде не коммутативно. Это означает, что для матриц не выполняется правило независимости произведения от перестановки множителей:

In [36]:
A = np.matrix('12 7; 8 11')
B = np.matrix('5 5; 9 3')
L = A.dot(B)
R = B.dot(A)
print(L)
print(R)

[[123  81]
 [139  73]]
[[100  90]
 [132  96]]


Свойство 4. Произведение заданной матрицы на единичную равно исходной матрице:

In [37]:
A = np.matrix('5 9; 12 7')
E = np.matrix('1 0; 0 1')
L = E.dot(A)
R = A.dot(E)
print(L)
print(R)
print(A)

[[ 5  9]
 [12  7]]
[[ 5  9]
 [12  7]]
[[ 5  9]
 [12  7]]


Свойство 5. Произведение заданной матрицы на нулевую матрицу равно нулевой матрице:

In [38]:
A = np.matrix('5 9; 12 7')
Z = np.matrix('0 0; 0 0')
L = Z.dot(A)
R = A.dot(Z)
print(L)
print(R)
print(Z)

[[0 0]
 [0 0]]
[[0 0]
 [0 0]]
[[0 0]
 [0 0]]


# Определитель матрицы

Свойство 1. Определитель матрицы остается неизменным при ее транспонировании:

In [39]:
A = np.matrix('7 1 -8; 15 42 16; 7 5 6')
print(A)
print(A.T)
det_A = round(np.linalg.det(A), 3)
det_A_t = round(np.linalg.det(A.T), 3)
print(det_A)
print(det_A_t)

[[ 7  1 -8]
 [15 42 16]
 [ 7  5  6]]
[[ 7 15  7]
 [ 1 42  5]
 [-8 16  6]]
2978.0
2978.0


Свойство 2. Если у матрицы есть строка или столбец, состоящие из нулей, то определитель такой матрицы равен нулю:

In [40]:
A = np.matrix('7 1 -8; 15 42 16; 7 5 6')
print(A)
np.linalg.det(A)

[[ 7  1 -8]
 [15 42 16]
 [ 7  5  6]]


2977.9999999999986

Свойство 3. При перестановке строк матрицы знак ее определителя меняется на противоположный:

In [41]:
A = np.matrix('7 1 -8; 15 42 16; 7 5 6')
print(A)
B = np.matrix('18 4 -12; -1 -2 3; 5 1 5')
print(B)
round(np.linalg.det(A), 3)
round(np.linalg.det(B), 3)

[[ 7  1 -8]
 [15 42 16]
 [ 7  5  6]]
[[ 18   4 -12]
 [ -1  -2   3]
 [  5   1   5]]


-262.0

Свойство 4. Если у матрицы есть две одинаковые строки, то ее определитель равен нулю:

In [43]:
A = np.matrix('-5 5 1; 0 12 3; -5 5 1')
print(A)
np.linalg.det(A)

[[-5  5  1]
 [ 0 12  3]
 [-5  5  1]]


0.0

Свойство 5. Если все элементы строки или столбца матрицы умножить на какое-то число, то и определитель будет умножен на это число:

In [45]:
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
print(A)
k = 2
B = A.copy()
B[2, :] = k * B[2, :]
print(B)
det_A = round(np.linalg.det(A), 3)
det_B = round(np.linalg.det(B), 3)
det_A * k
det_B

[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]
[[-4 -1  2]
 [10  4 -1]
 [16  6  2]]


-28.0

Свойство 6. Если все элементы строки или столбца можно представить как сумму двух слагаемых, то определитель такой матрицы равен сумме определителей двух соответствующих матриц:

In [46]:
A = np.matrix('-4 -1 2; -4 -1 2; 8 3 1')
B = np.matrix('-4 -1 2; 8 3 2; 8 3 1')
C = A.copy()
C[1, :] += B[1, :]
print(C)
print(A)
print(B)
round(np.linalg.det(C), 3)
round(np.linalg.det(A), 3) + round(np.linalg.det(B), 3)

[[-4 -1  2]
 [ 4  2  4]
 [ 8  3  1]]
[[-4 -1  2]
 [-4 -1  2]
 [ 8  3  1]]
[[-4 -1  2]
 [ 8  3  2]
 [ 8  3  1]]


4.0

Свойство 7. Если к элементам одной строки прибавить элементы другой строки, умноженные на одно и тоже число, то определитель матрицы не изменится:

In [50]:
A = np.matrix('-5 5 1; 0 12 3; -5 5 2')
k = 2
B = A.copy()
B[1, :] = B[1, :] + k * B[0, :]
print(A)
print(B)
round(np.linalg.det(A), 3)
round(np.linalg.det(B), 3)

[[-5  5  1]
 [ 0 12  3]
 [-5  5  2]]
[[ -5   5   1]
 [-10  22   5]
 [ -5   5   2]]


-60.0

Свойство 8. Если строка или столбец матрицы является линейной комбинацией других строк (столбцов), то определитель такой матрицы равен нулю:

In [54]:
A = np.matrix('5 5 1; 1 12 3; -5 5 3')
print(A)
k = 2
A[1, :] = A[0, :] + k * A[2, :]
round(np.linalg.det(A), 3)

[[ 5  5  1]
 [ 1 12  3]
 [-5  5  3]]


0.0

Свойство 9. Если матрица содержит пропорциональные строки, то ее определитель равен нулю:

In [55]:
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
print(A)
k = 2
A[1, :] = k * A[0, :]
print(A)
round(np.linalg.det(A), 3)

[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]
[[-4 -1  2]
 [-8 -2  4]
 [ 8  3  1]]


0.0

# Обратная матрица

In [56]:
A = np.matrix('1. -3.; 2. 5.')
A_inv = np.linalg.inv(A)
A_inv_inv = np.linalg.inv(A_inv)
print(A)
print(A_inv_inv)

[[ 1. -3.]
 [ 2.  5.]]
[[ 1. -3.]
 [ 2.  5.]]


Свойство 2. Обратная матрица транспонированной матрицы равна транспонированной матрице от обратной матрицы:

In [57]:
A = np.matrix('1. -3.; 2. 5.')
L = np.linalg.inv(A.T)
R = (np.linalg.inv(A)).T
print(L)
print(R)

[[ 0.45454545 -0.18181818]
 [ 0.27272727  0.09090909]]
[[ 0.45454545 -0.18181818]
 [ 0.27272727  0.09090909]]


Свойство 3. Обратная матрица произведения матриц равна произведению обратных матриц:

In [58]:
A = np.matrix('1. -3.; 2. 5.')
B = np.matrix('7. 6.; 1. 8.')
L = np.linalg.inv(A.dot(B))
R = np.linalg.inv(B).dot(np.linalg.inv(A))
print(L)
print(R)

[[ 0.09454545  0.03272727]
 [-0.03454545  0.00727273]]
[[ 0.09454545  0.03272727]
 [-0.03454545  0.00727273]]
